django_blog/urls.py
from django.urls import path

from . import views

app_name = "blog"
urlpatterns = [

    path("", views.IndexView.as_view(), name="index"),
    path("category/<str:category_slug>/", views.IndexView.as_view(), name="category_detail"),
    path("<slug:slug>/", views.PostDetailView.as_view(), name="post_detail"),
]

learning/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('blog/', include("blog.urls")),
    path('admin/', admin.site.urls),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from django.contrib.auth.models import User
from .validation import validate_only_letters, validate_excluding_special_chars
import datetime


# Create your models here.

class Category(models.Model):

    name = models.CharField(max_length=200, validators=[validate_only_letters], unique=True)
    slug = models.SlugField(unique=True, null=True, blank=True, max_length=200) 
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    parent_category = models.ForeignKey('self',
                                        null=True,
                                        blank=True,
                                        on_delete=models.SET_NULL,
                                        related_name='subcategories')
    
    class Meta:
        constraints = [ models.UniqueConstraint(fields=['parent_category'], name='unique_parent_category') ]


    def __str__(self):
        return self.name



def get_or_create_default_category():
    category = Category.objects.get_or_create(name="no category")
    return category.index


class Post(models.Model):
    category = models.ForeignKey(Category, null=True, on_delete=models.SET_NULL, default=get_or_create_default_category)

    image = models.ImageField(upload_to="images/", default="images/default_image.png")

    title = models.CharField(max_length=200, validators=[validate_excluding_special_chars])
    slug = models.SlugField(unique=True, null=True, blank=True, max_length=200) 
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    description = models.TextField()
    pub_date = models.DateTimeField("date published")
     
    author = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.title

    def get_image_url(self):
        return f"{self.image.url}"

    def was_published_recently(self):
        return timezone.now() - datetime.timedelta(days=1) <= self.pub_date <= timezone.now() 

    def get_excerpt(self, length=75):
        return self.description[:length] + ('...' if len(self.description) > length else '') 

django_blog/models.py
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from django.contrib.auth.models import User
from .validation import validate_only_letters, validate_excluding_special_chars
import datetime


# Create your models here.

class Category(models.Model):

    name = models.CharField(max_length=200, validators=[validate_only_letters], unique=True)
    slug = models.SlugField(unique=True, null=True, blank=True, max_length=200) 
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    parent_category = models.ForeignKey('self',
                                        null=True,
                                        blank=True,
                                        on_delete=models.SET_NULL,
                                        related_name='subcategories')
    
    class Meta:
        constraints = [ models.UniqueConstraint(fields=['parent_category'], name='unique_parent_category') ]


    def __str__(self):
        return self.name

    def posts_count(self):
        return self.post_set.all().count()


def get_or_create_default_category():
    category = Category.objects.get_or_create(name="no category")
    return category.index


class Post(models.Model):
    category = models.ForeignKey(Category, null=True, on_delete=models.SET_NULL, default=get_or_create_default_category)

    image = models.ImageField(upload_to="images/", default="images/default_image.png")

    title = models.CharField(max_length=200, validators=[validate_excluding_special_chars])
    slug = models.SlugField(unique=True, null=True, blank=True, max_length=200) 
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    description = models.TextField()
    pub_date = models.DateTimeField("date published")
     
    author = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.title

    def get_image_url(self):
        return f"{self.image.url}"

    def was_published_recently(self):
        return timezone.now() - datetime.timedelta(days=1) <= self.pub_date <= timezone.now() 

    def get_excerpt(self, length=75):
        return self.description[:length] + ('...' if len(self.description) > length else '') 

django_blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.utils import timezone
from django.core.paginator import Paginator

from .models import Category, Post

# Create your views here.

class PostDetailView(DetailView):

    model = Post
    template_name = "blog/detail.html"

    

class IndexView(ListView):

    paginate_by = 2

    template_name = "blog/index.html"
    context_object_name = "posts"

    def get_queryset(self):
        
        queryset = Post.objects.all()
        sorting_option = self.request.GET.get("sorting")

        if sorting_option == "by_date_asc":
            queryset = queryset.order_by("pub_date")
         
        if sorting_option == "by_date_desc":
            queryset = queryset.order_by("-pub_date")

        return queryset

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        
        context["categories"] = Category.objects.exclude(name="no category")

        sorting_option = self.request.GET.get("sorting", "")
        context["sorting"] = sorting_option

        category_slug = self.kwargs.get("category_slug")
        
        if category_slug:
            category = get_object_or_404(Category, slug=category_slug)

            posts = Post.objects.filter(category=category)

            if sorting_option == "by_date_asc":
                posts = posts.order_by("pub_date")
            
            if sorting_option == "by_date_desc":
                posts = posts.order_by("-pub_date")
            
            context["posts"] = posts

            paginator = Paginator(posts, 2)

            page_number = self.request.GET.get("page")
            page_obj = paginator.get_page(page_number)

            context["page_obj"] = page_obj

        else:
            context["posts"] = self.get_queryset()
            
            posts = self.get_queryset()

            paginator = Paginator(posts, 2)

            page_number = self.request.GET.get("page")
            page_obj = paginator.get_page(page_number)

            context["page_obj"] = page_obj


        return context

    
    def post(self, request, *args, **kwargs):
        
        sorting_option = request.POST.get('sorting')

        if sorting_option:
            # Przekierowanie z parametrem sorting
            if 'category_slug' in self.kwargs:
                category_slug = self.kwargs['category_slug']
                return redirect('{}?sorting={}'.format(
                    reverse('blog:category_detail', kwargs={'category_slug': category_slug}),
                    sorting_option))
            else:
                return redirect('{}?sorting={}'.format(
                    reverse('blog:index'),
                    sorting_option))

        return super().get(request, *args, **kwargs)

django_blog/templates/blog/detail.html
<!DOCTYPE HTML>
<html>
<head>
	<meta charset="UTF-8"> 
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{{ post.title }}</title>
	{% load static %}
	<link rel="stylesheet" href="{% static 'blog/post_detail/style.css' %}">
	<style>
		.post-image{
			width: 820px;
			height: 461px;
			background-image: url("{{ post.get_image_url }}");
			background-attachment: inherit;
			background-size: cover;
			background-position: center;
		}
	</style>
</head>
<body>
	<a href="{% url 'blog:index' %}">Back to blog</a>
	<div class="post-container">
		<div class="post-title"><h1>{{ post.title }}</h1></div>
		<div class="post-image"></div>
		<div class="post-author">{% if post.author %}Autor: {{ post.author }}{% endif %}</div>
		<div class="post-description"><p>{{ post.description }}</p></div>
	</div>

</body>
</html>

django_blog/templates/blog/index.html
<!DOCTYPE HTML>
<html>
<head>
	<meta charset="UTF-8"> 
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Blog</title>
	{% load static %}
	<link rel="stylesheet" href="{% static 'blog/style.css' %}">
	{% if posts %}
		{% for post in page_obj %}
			<style>
				.post-image{{ forloop.counter }}{
					width: 225px;
					height: 225px;
					background-image: url("{{ post.get_image_url }}");
					background-attachment: inherit;
					background-size: cover;
					background-position: center;
				}
			</style>
		{% endfor %}
	{% endif %}
</head>
<body>
	<div class="flex-body-container">
	{% if categories %}
		<div class="flex-category-container">
			<span class="category-link" name="category" id="cat-default"><a href="{% url 'blog:index' %}">All articles</a></span>
			{% for category in categories %}
			<span class="category-link" name="category" id="cat{{ forloop.counter }}"><a href="{% url 'blog:category_detail' category.slug %}">{{ category.name }}</a></span>
			{% endfor %}
	{% else %}
		<p>There aren't categories.</p>
	{% endif %}
		</div>
	<div class="flex-sorting-container">
		<form method="GET" action="">
			<select id="menu-sorting sort" name="sorting" onchange="this.form.submit()">
				<option value="by_date_asc" {% if sorting == 'by_date_asc' %}selected{% endif %}>order by date ASC</option>
				<option value="by_date_desc" {% if sorting == 'by_date_desc' %}selected{% endif %}>order by date DESC</option>
			</select>
		</form>
	</div>

	{% if posts %}
		<div class="post-container">
		{% for post in page_obj %}
			<a href="{% url 'blog:post_detail' post.slug %}">
				<div class="post-template">
					<div class="post-image{{ forloop.counter }}"></div>
					<span class="post-title">{{ post.title }}</span>
					<div class="post-excerpt">{{ post.get_excerpt }}</div>
					<div class="post-author">{% if post.author %}Autor: {{ post.author }}{% endif %}</div>
				</div>
			</a>
		{% endfor %}
	{% else %}
		<p>There aren't posts.</p>
	{% endif %}
		</div>
		<div class="pagination">
		    <span class="step-links">
			{% if page_obj.has_previous %}
			    <a href="?page=1">&laquo; first</a>
			    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
			{% endif %}

			<span class="current">
			    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
			</span>

			{% if page_obj.has_next %}
			    <a href="?page={{ page_obj.next_page_number }}">next</a>
			    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
			{% endif %}
		    </span>
		</div>
	</div>
</body>
</html>